dist: trusty

language: php
cache:
  bundler: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"

php:
  - 7.3

before_install:
  - composer self-update
  - composer --version

  # Composer Configurations.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1
  - export COMPOSER_MEMORY_LIMIT=-1

install:
  - git checkout $TRAVIS_COMMIT
  - composer install
  - composer require drupal/coder

script:
  - ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer/
  - ./vendor/bin/phpcs --standard=Drupal docroot/profiles/contrib/ezcontent
  - ./vendor/bin/phpcs --standard=DrupalPractice docroot/profiles/contrib/ezcontent
